Repository paion-data/astraios, pull requests merged in 2023-09, with the labels that each got.

#15 Deploy for serving Nexus Graph
  .github/actions/create-mvn-settings/action.yml
  .github/workflows/ci-cd.yml
  README.md
  checkstyle-suppressions.xml
  hashicorp/images/nexusgraph-astraios.pkr.hcl
  hashicorp/images/nginx-ssl.conf
  hashicorp/instances/main.tf
  hashicorp/scripts/setup.sh
Labels: CI/CD, MERGEABLE

#16 Add tests for Docker Compose
  .github/workflows/ci-cd.yml
  docker-compose.yml
  src/test/groovy/com/paiondata/astraios/application/AbstractITSpec.groovy
  src/test/groovy/com/paiondata/astraios/application/DockerComposeITSpec.groovy
  src/test/groovy/com/paiondata/astraios/application/ResourceConfigITSpec.groovy
Labels: CI/CD, MERGEABLE

#17 Implement OAuth2 access token validation
  docs/docs/development.md
  docs/docs/img/oauth2-filtering.drawio
  docs/docs/img/oauth2-filtering.png
  docs/docs/security.md
  src/main/java/com/paiondata/astraios/application/BinderFactory.java
  src/main/java/com/paiondata/astraios/application/ResourceConfig.java
  src/main/java/com/paiondata/astraios/web/filters/OAuth2Filter.java
  src/main/java/com/paiondata/astraios/web/filters/oauth/AccessTokenValidator.java
  src/main/java/com/paiondata/astraios/web/filters/oauth/JwtTokenValidator.java
  src/test/groovy/com/paiondata/astraios/application/AbstractITSpec.groovy
  src/test/groovy/com/paiondata/astraios/application/DockerComposeITSpec.groovy
  src/test/groovy/com/paiondata/astraios/web/filters/CorsFilterSpec.groovy
  src/test/groovy/com/paiondata/astraios/web/filters/OAuth2FilterSpec.groovy
Labels: MERGEABLE, OAUTH2

#18 Implement JWT (ES384) access token validator
  docs/docs/security.md
  pom.xml
  src/main/java/com/paiondata/astraios/application/BinderFactory.java
  src/main/java/com/paiondata/astraios/application/ResourceConfig.java
  src/main/java/com/paiondata/astraios/config/OAuthConfig.java
  src/main/java/com/paiondata/astraios/web/filters/OAuthFilter.java
  src/main/java/com/paiondata/astraios/web/filters/oauth/ES384JwtTokenValidator.java
  src/main/java/com/paiondata/astraios/web/filters/oauth/JwtTokenValidator.java
  src/test/groovy/com/paiondata/astraios/application/AbstractITSpec.groovy
  src/test/groovy/com/paiondata/astraios/application/ResourceConfigSpec.groovy
  src/test/groovy/com/paiondata/astraios/web/filters/OAuthFilterSpec.groovy
  src/test/groovy/com/paiondata/astraios/web/filters/oauth/ES384JwtTokenValidatorSpec.groovy
Labels: MERGEABLE, OAUTH2

#19 Add OAuth runtime config
  .github/workflows/ci-cd.yml
Labels: CI/CD, MERGEABLE, SECURITY

#20 Enhance documentation
  docs/docs/development.md
  docs/docs/elide.md
  src/test/groovy/com/paiondata/astraios/web/filters/oauth/ES384JwtTokenValidatorSpec.groovy
Labels: DOCUMENTATION, MERGEABLE

#21 Enable checkstyle Javadoc check on class/interface and method
  checkstyle.xml
  docker-compose.yml
  docs/docs/configuration.md
  pom.xml
  src/main/java/com/paiondata/astraios/application/BinderFactory.java
  src/main/java/com/paiondata/astraios/application/ResourceConfig.java
  src/main/java/com/paiondata/astraios/config/ApplicationConfig.java
  src/main/java/com/paiondata/astraios/config/JpaDatastoreConfig.java
  src/main/java/com/paiondata/astraios/config/OAuthConfig.java
  src/main/java/com/paiondata/astraios/web/filters/CorsFilter.java
  src/main/java/com/paiondata/astraios/web/filters/OAuthFilter.java
  src/test/groovy/com/paiondata/astraios/application/AbstractITSpec.groovy
  src/test/groovy/com/paiondata/astraios/application/DockerComposeITSpec.groovy
  src/test/groovy/com/paiondata/astraios/application/ResourceConfigITSpec.groovy
  src/test/groovy/com/paiondata/astraios/application/ResourceConfigSpec.groovy
  src/test/groovy/com/paiondata/astraios/web/filters/oauth/ES384JwtTokenValidatorSpec.groovy
  src/test/java/com/paiondata/astraios/models/Book.java
Labels: BUG, DOCUMENTATION, MERGEABLE, REFACTORING

#22 Enable GraphQL endpoints
  Dockerfile
  docs/docs/development.md
  docs/docs/img/download-jetty.png
  pom.xml
  src/main/java/com/paiondata/astraios/application/BinderFactory.java
  src/main/java/com/paiondata/astraios/application/ResourceConfig.java
  src/test/groovy/com/paiondata/astraios/application/ResourceConfigITSpec.groovy
Labels: MERGEABLE, ELIDE MIDDLEWARE

#24 Remove websocket Jetty module from deployment
  docs/docs/configuration.md
  hashicorp/scripts/setup.sh
  src/main/java/com/paiondata/astraios/application/ResourceConfig.java
  src/test/groovy/com/paiondata/astraios/application/AbstractITSpec.groovy
  src/test/groovy/com/paiondata/astraios/application/ResourceConfigITSpec.groovy
  src/test/groovy/com/paiondata/astraios/application/ResourceConfigSpec.groovy
Labels: BUG, CI/CD, MERGEABLE

#25 Support specifying POM properties via settings.xml file
  .github/actions/create-mvn-settings/action.yml
  .github/workflows/ci-cd.yml
  docs/docs/development.md
  docs/docs/img/load-m2-settings.png
  pom.xml
Labels: DOCUMENTATION, MERGEABLE, CONFIG

#26 Fix broken links in documentation
  docs/docs/development.md
  docs/docs/elide.md
Labels: BUG, DOCUMENTATION, MERGEABLE

#27 Add GraphQL paging tests
  src/test/groovy/com/paiondata/astraios/application/ResourceConfigITSpec.groovy
Labels: MERGEABLE, ELIDE MIDDLEWARE

#28 Send Astraios logs to ELK
  .github/workflows/ci-cd.yml
  .gitignore
  hashicorp/images/filebeat.yml
  hashicorp/images/nexusgraph-astraios.pkr.hcl
  hashicorp/instances/main.tf
  hashicorp/scripts/setup.sh
  pom.xml
  src/main/resources/logback.xml
Labels: CI/CD, MERGEABLE, CONFIG

#29 Support doc language switching
  docs/README.md
  docs/docs/img/ci-cd.drawio
  docs/docs/img/ci-cd.png
  docs/docs/img/setup-sentry-1.png
  docs/docs/img/setup-sentry-2.png
  docs/docs/img/setup-sentry-3.png
  docs/docusaurus.config.js
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/elide.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/img/docker-compose.drawio
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/img/docker-compose.png
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/img/download-jetty.png
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/img/resource-binding.drawio
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/img/resource-binding.png
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/setup.md
  node_modules/.yarn-integrity
  yarn.lock
Labels: BUG, DOCUMENTATION, MERGEABLE

#30 Update
  .github/workflows/ci-cd.yml
  hashicorp/images/nginx-ssl.conf
  hashicorp/instances/nexusgraph-astraios.tf
Labels: MERGEABLE, REFACTORING

#31 Add preflight request filter
  src/main/java/com/paiondata/astraios/web/filters/CorsFilter.java
  src/test/groovy/com/paiondata/astraios/application/ResourceConfigITSpec.groovy
  src/test/groovy/com/paiondata/astraios/web/filters/CorsFilterSpec.groovy
Labels: BUG, NEED CHANGES
