Repository paion-data/astraios, pull requests merged in 2023-08, with the labels that each got.

#1 Initial release
  .github/workflows/ci-cd.yml
  .yamllint
  Astraios-Project-intellij-code-style.xml
  Dockerfile
  README.md
  checkstyle.xml
  docs/README.md
  docs/blog/authors.yml
  docs/docs/ci-cd.md
  docs/docs/development.md
  docs/docs/intro.md
  docs/docs/sentry.md
  docs/docs/setup.md
  docs/docusaurus.config.js
  hashicorp/images/aws-jersey-ws.pkr.hcl
  hashicorp/images/nginx-ssl.conf
  hashicorp/instances/main.tf
  hashicorp/scripts/setup.sh
  markdownlint.rb
  pom.xml
  src/main/java/com/paiondata/astraios/application/ApplicationConfig.java
  src/main/java/com/paiondata/astraios/application/BinderFactory.java
  src/main/java/com/paiondata/astraios/application/ResourceConfig.java
  src/main/java/com/paiondata/astraios/web/endpoints/DataServlet.java
  src/main/java/com/paiondata/astraios/web/filters/CorsFilter.java
  src/main/java/com/qubitpi/ws/jersey/template/cache/LruCache.java
  src/main/resources/logback.xml
  src/test/groovy/com/paiondata/astraios/DataServletITSpec.groovy
  src/test/groovy/com/paiondata/astraios/JettyServerFactorySpec.groovy
  src/test/groovy/com/paiondata/astraios/web/endpoints/DataServletSpec.groovy
  src/test/groovy/com/paiondata/astraios/web/filters/CorsFilterSpec.groovy
  src/test/groovy/com/qubitpi/ws/jersey/template/cache/LruCacheSpec.groovy
  src/test/java/com/paiondata/astraios/JettyServerFactory.java
  src/test/java/com/paiondata/astraios/resource/TestEndpoint.java
Labels: CI/CD, DOCUMENTATION, MERGEABLE

#2 Upgrade to JDK 17
  .github/workflows/ci-cd.yml
  Dockerfile
  docs/docs/development.md
  docs/docs/img/download-jetty.png
  docs/docs/setup.md
  hashicorp/instances/main.tf
  hashicorp/scripts/setup.sh
  pom.xml
Labels: BREAKING CHANGE, BUG, CI/CD, DOCUMENTATION

#4 Implement persistence layer using Elide
  docs/docs/development.md
  pom.xml
  src/main/java/com/paiondata/astraios/application/ApplicationConfig.java
  src/main/java/com/paiondata/astraios/application/BinderFactory.java
  src/main/java/com/paiondata/astraios/application/ResourceConfig.java
  src/main/java/com/paiondata/astraios/web/endpoints/DataServlet.java
  src/main/java/com/paiondata/astraios/web/filters/CorsFilter.java
  src/test/groovy/com/paiondata/astraios/DataServletITSpec.groovy
  src/test/groovy/com/paiondata/astraios/JettyServerFactorySpec.groovy
  src/test/groovy/com/paiondata/astraios/web/endpoints/DataServletSpec.groovy
  src/test/groovy/com/paiondata/astraios/web/filters/CorsFilterSpec.groovy
  src/test/java/com/paiondata/astraios/JettyServerFactory.java
  src/test/java/com/paiondata/astraios/resource/TestEndpoint.java
Labels: MERGEABLE, PERSISTENCE LAYER

#7 Fix EC2 instance name
  docs/docs/setup.md
  hashicorp/instances/main.tf
Labels: BUG, CI/CD, MERGEABLE

#8 Support external package injection & Add integration tests
  .github/actions/create-mvn-settings/action.yml
  .github/workflows/ci-cd.yml
  docker-compose.yml
  docs/docs/development.md
  docs/docs/img/docker-compose.drawio
  docs/docs/img/docker-compose.png
  docs/docs/setup.md
  mysql-init.sql
  pom.xml
  src/main/java/com/paiondata/astraios/application/BinderFactory.java
  src/main/java/com/paiondata/astraios/application/ResourceConfig.java
  src/main/java/com/paiondata/astraios/config/ApplicationConfig.java
  src/main/java/com/paiondata/astraios/config/JpaDatastoreConfig.java
  src/main/java/com/paiondata/astraios/web/filters/CorsFilter.java
  src/test/groovy/com/paiondata/astraios/application/ResourceConfigITSpec.groovy
  src/test/java/com/paiondata/astraios/models/Book.java
  src/test/resources/application.properties
  src/test/resources/jpadatastore.properties
Labels: CI/CD, DOCUMENTATION, MERGEABLE

#9 Avoid SonarCloud caches
  .github/workflows/ci-cd.yml
Labels: BUG, MERGEABLE

#10 Fix flaky dependency injection
  docs/docs/ci-cd.md
  pom.xml
  src/main/java/com/paiondata/astraios/application/BinderFactory.java
  src/main/java/com/paiondata/astraios/application/ResourceConfig.java
Labels: BUG

#11 Enhance documentations
  docs/docs/ci-cd.md
  docs/docs/development.md
  docs/docs/elide.md
  docs/docs/img/resource-binding.drawio
  docs/docs/img/resource-binding.png
  docs/docs/sentry.md
  docs/docs/setup.md
Labels: DOCUMENTATION, MERGEABLE

#12 Fix patch request CORE error
  src/main/java/com/paiondata/astraios/web/filters/CorsFilter.java
Labels: BUG, MERGEABLE
