Repository paion-data/astraios, pull requests merged in 2023-10, with the labels that each got.

#33 Align Dockerfile for test with production deployment logic
  .github/workflows/ci-cd.yml
  Dockerfile
  Dockerfile-startup.sh
  hashicorp/images/nexusgraph-astraios.pkr.hcl
  hashicorp/images/nginx-ssl.conf
  hashicorp/images/variables.pkr.hcl
  hashicorp/instances/nexusgraph-astraios.tf
  hashicorp/scripts/nexusgrah-astraios-pkr-setup.sh
  hashicorp/scripts/nexusgraph-astraios-tf-init.sh
  src/main/java/com/paiondata/astraios/config/OAuthConfig.java
Labels: BUG, NEED 1 REVIEW

#32 Delete junk files
  node_modules/.yarn-integrity
  yarn.lock
Labels: BUG, MERGEABLE

#35 Change WAR file pick up location in order to fit a general deployment pattern
  .github/actions/setup/action.yml
  .github/workflows/ci-cd.yml
Labels: BUG, MERGEABLE, REFACTORING

#36 Add demo video
  .mdlrc
  README.md
Labels: MERGEABLE, DOCUMENTATION
