Repository paion-data/astraios, pull requests merged in 2023-12, with the labels that each got.

#76 Enhance documentation
  docs/docs/development.md
  docs/docs/elide/analytics.mdx
  docs/docs/elide/audit.md
  docs/docs/elide/data-model.md
  docs/docs/elide/datastores.mdx
  docs/docs/elide/features.md
  docs/docs/elide/index.md
  docs/docs/elide/openapi.md
  docs/docs/elide/performance.md
  docs/docs/elide/security.mdx
  docs/docs/img/graphiql-query-example.png
  docs/docs/img/resource-binding.drawio
  docs/docs/img/resource-binding.png
  docs/docs/intro.mdx
Labels: MERGEABLE, DOCUMENTATION

#74 Centralize AMI test into hashicorp-aws & Enhance product page
  .github/actions/ci-setup/action.yml
  .github/workflows/ci-cd.yml
  docs/.gitignore
  docs/CNAME
  docs/babel.config.js
  docs/docs/configuration.md
  docs/docs/elide/analytics.mdx
  docs/docs/elide/audit.md
  docs/docs/elide/clientapis/asyncapi.mdx
  docs/docs/elide/clientapis/graphql.mdx
  docs/docs/elide/clientapis/index.md
  docs/docs/elide/clientapis/jsonapi.mdx
  docs/docs/elide/clientapis/subscriptions.mdx
  docs/docs/elide/data-model.md
  docs/docs/elide/datastores.mdx
  docs/docs/elide/features.md
  docs/docs/elide/openapi.md
  docs/docs/elide/performance.md
  docs/docs/elide/security.mdx
  docs/docs/intro.mdx
  docs/docs/setup.md
  docs/docusaurus.config.ts
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/elide.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/setup.md
  docs/package.json
  docs/sidebars.ts
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.module.css
  docs/src/pages/index.tsx
  docs/static/img/apache.svg
  docs/static/img/developer.svg
  docs/static/img/security.svg
  docs/yarn.lock
  hashicorp/images/example.pkrvars.hcl
  hashicorp/images/filebeat.yml.example
  hashicorp/images/nginx.config.example
  hashicorp/images/ssl-cert-file.example
  hashicorp/images/ssl-cert-key-file.example
  hashicorp/instances/example.tfvars
Labels: BUG, CI/CD, MERGEABLE, DOCUMENTATION

#78 Front page improvements
  .github/workflows/ci-cd.yml
  README.md
  docs/docusaurus.config.ts
  docs/src/pages/index.tsx
Labels: MERGEABLE, DOCUMENTATION

#79 Centralize JDK setup in CI/CD
  .github/actions/cd-setup/action.yml
  .github/actions/ci-setup/action.yml
Labels: CI/CD, MERGEABLE, REFACTORING

#80 Add CI/CD documentations
  docs/docs/configuration.md
Labels: MERGEABLE, DOCUMENTATION

#81 OAuth is disabled by default but can be overridden to enable in Docker Compose
  docker-compose.yml
  docs/docs/development.md
  docs/static/img/cors.svg
  docs/static/img/docusaurus.png
  docs/static/img/groovy.svg
  docs/static/img/hashicorp-logos/Logo/Primary_Horizontal/CMYK/AI/HashiCorp_PrimaryLogo_Black_CMYK.ai
  docs/static/img/hashicorp-logos/Logo/Primary_Horizontal/CMYK/AI/HashiCorp_PrimaryLogo_White_CMYK.ai
  docs/static/img/hashicorp-logos/Logo/Primary_Horizontal/CMYK/EPS/HashiCorp_PrimaryLogo_Black_CMYK.eps
  docs/static/img/hashicorp-logos/Logo/Primary_Horizontal/CMYK/EPS/HashiCorp_PrimaryLogo_White_CMYK.eps
  docs/static/img/hashicorp-logos/Logo/Primary_Horizontal/RGB/AI/HashiCorp_PrimaryLogo_Black_RGB.ai
  docs/static/img/hashicorp-logos/Logo/Primary_Horizontal/RGB/AI/HashiCorp_PrimaryLogo_White_RGB.ai
  docs/static/img/hashicorp-logos/Logo/Primary_Horizontal/RGB/PNG/HashiCorp_PrimaryLogo_Black_RGB.png
  docs/static/img/hashicorp-logos/Logo/Primary_Horizontal/RGB/PNG/HashiCorp_PrimaryLogo_White_RGB.png
  docs/static/img/hashicorp-logos/Logo/Primary_Horizontal/RGB/SVG/HashiCorp_PrimaryLogo_Black_RGB.svg
  docs/static/img/hashicorp-logos/Logo/Primary_Horizontal/RGB/SVG/HashiCorp_PrimaryLogo_White_RGB.svg
  docs/static/img/hashicorp-logos/Logo/Secondary_Vertical/CMYK/AI/HashiCorp_VerticalLogo_Black_CMYK.ai
  docs/static/img/hashicorp-logos/Logo/Secondary_Vertical/CMYK/AI/HashiCorp_VerticalLogo_White_CMYK.ai
  docs/static/img/hashicorp-logos/Logo/Secondary_Vertical/CMYK/EPS/HashiCorp_VerticalLogo_Black_CMYK.eps
  docs/static/img/hashicorp-logos/Logo/Secondary_Vertical/CMYK/EPS/HashiCorp_VerticalLogo_White_CMYK.eps
  docs/static/img/hashicorp-logos/Logo/Secondary_Vertical/RGB/AI/HashiCorp_VerticalLogo_Black_RGB.ai
  docs/static/img/hashicorp-logos/Logo/Secondary_Vertical/RGB/AI/HashiCorp_VerticalLogo_White_RGB.ai
  docs/static/img/hashicorp-logos/Logo/Secondary_Vertical/RGB/PNG/HashiCorp_VerticalLogo_Black_RGB.png
  docs/static/img/hashicorp-logos/Logo/Secondary_Vertical/RGB/PNG/HashiCorp_VerticalLogo_White_RGB.png
  docs/static/img/hashicorp-logos/Logo/Secondary_Vertical/RGB/SVG/HashiCorp_VerticalLogo_Black_RGB.svg
  docs/static/img/hashicorp-logos/Logo/Secondary_Vertical/RGB/SVG/HashiCorp_VerticalLogo_White_RGB.svg
  docs/static/img/hashicorp-logos/Logomark/CMYK/AI/HashiCorp_Icon_Black_CMYK.ai
  docs/static/img/hashicorp-logos/Logomark/CMYK/AI/HashiCorp_Icon_White_CMYK.ai
  docs/static/img/hashicorp-logos/Logomark/CMYK/EPS/HashiCorp_Icon_Black_CMYK.eps
  docs/static/img/hashicorp-logos/Logomark/CMYK/EPS/HashiCorp_Icon_White_CMYK.eps
  docs/static/img/hashicorp-logos/Logomark/RGB/AI/HashiCorp_Icon_Black_RGB.ai
  docs/static/img/hashicorp-logos/Logomark/RGB/AI/HashiCorp_Icon_White_RGB.ai
  docs/static/img/hashicorp-logos/Logomark/RGB/PNG/HashiCorp_Icon_Black_RGB.png
  docs/static/img/hashicorp-logos/Logomark/RGB/PNG/HashiCorp_Icon_White_RGB.png
  docs/static/img/hashicorp-logos/Logomark/RGB/SVG/HashiCorp_Icon_Black_RGB.svg
  docs/static/img/hashicorp-logos/Logomark/RGB/SVG/HashiCorp_Icon_White_RGB.svg
  docs/static/img/jersey-logo.ai
  logback/astraios.log
Labels: MERGEABLE, NEW FEATURE, DOCUMENTATION

#82 Add missing oauth config in Docker Compose
  docker-compose.yml
  docs/docs/development.md
  logback/astraios.log
Labels: BUG, MERGEABLE, DOCUMENTATION

#83 Enhance image rendering
  docs/docs/development.md
Labels: BUG, MERGEABLE, DOCUMENTATION

#84 Add new upstream trigger
  .github/workflows/ci-cd.yml
Labels: CI/CD, MERGEABLE

#85 Add documentation on enabling cascading delete on data model
  docs/docs/elide/data-model.md
  logback/astraios.2023-12-24.log
  logback/astraios.log
Labels: MERGEABLE, DOCUMENTATION

#86 Add Elide Async API internal diagram
  docs/docs/elide/clientapis/asyncapi.mdx
  docs/docs/elide/clientapis/img/elide-async-design.drawio
  docs/docs/elide/clientapis/img/elide-async-design.png
Labels: MERGEABLE, DOCUMENTATION

#87 Sync up with elide-doc
  docs/docs/elide/clientapis/asyncapi.mdx
  docs/docs/elide/clientapis/graphql-federation.md
  docs/docs/elide/clientapis/img/graphql-federation.png
  docs/docs/elide/clientapis/img/multiple-graphql-apis-federated.png
  docs/docs/elide/clientapis/img/multiple-graphql-apis.png
  docs/docs/elide/clientapis/jsonapi.mdx
Labels: MERGEABLE, DOCUMENTATION

#89 Remove SonarCloud
  .github/workflows/ci-cd.yml
  README.md
  docs/docs/configuration.md
  logback/astraios.2023-12-24.log
  logback/astraios.log
  pom.xml
Labels: CI/CD, MERGEABLE, REFACTORING

#90 Correct doc typo
  docs/docs/configuration.md
  docs/docs/intro.mdx
Labels: BUG, DOCUMENTATION

#88 Add documentation translation
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/configuration.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/img/instantiation-1.png
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/img/instantiation-2.png
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
Labels: MERGEABLE, DOCUMENTATION, INTERNATIONALIZATION

#92 Better elaboration on supporting JAX-RS only and not Spring
  docs/docs/intro.mdx
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
Labels: MERGEABLE, DOCUMENTATION

#93 Fix doc typo
  docs/docs/intro.mdx
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
Labels: BUG, MERGEABLE, DOCUMENTATION

#95 Better statement 'not supporting Spring'
  docs/docs/intro.mdx
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
Labels: MERGEABLE, DOCUMENTATION

#94 Replace cglib with ByteBuddy
  pom.xml
Labels: MERGEABLE, REFACTORING

#97 Add documentation on enabling auto unused import removal
  docs/docs/setup.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/setup.md
Labels: MERGEABLE, DOCUMENTATION

#98 Fix doc typo
  docs/docs/setup.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/setup.md
Labels: BUG, MERGEABLE, DOCUMENTATION
