Repository paion-data/astraios, pull requests merged in 2024-07, with the labels that each got.

#141 Added deployment documentation for production environments
  docs/docs/deployment.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/configuration.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/deployment.md
Labels: MERGEABLE, DOCUMENTATION

#142 Remove 'No Spring' disclosure
  .github/workflows/ci-cd.yml
  docs/docs/intro.mdx
Labels: DOCUMENTATION, NEED 1 REVIEW

#138 Change all payload file from json to graphql
  src/test/java/com/paiondata/astraios/SpringbootITSpec.java
  src/test/resources/payload/create-book.graphql
  src/test/resources/payload/create-book.json
  src/test/resources/payload/page-sort.graphql
  src/test/resources/payload/page-sort.json
  src/test/resources/payload/update-book.graphql
  src/test/resources/payload/update-book.json
Labels: MERGEABLE, REFACTORING, NEED CHANGES
