Repository paion-data/astraios, pull requests merged in 2024-05, with the labels that each got.

#117 Resolve some issues with script runtime
  docs/docs/intro.mdx
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
  quickstart.sh
Labels: BUG, MERGEABLE

#119 Fix broken CI/CD
  .github/workflows/ci-cd.yml
  .lycheeignore
  .mdlrc
  .yamllint
  docs/docs/development.md
  markdownlint.rb
  quickstart.sh
  settings.xml.example
  src/test/resources/application.properties
Labels: BUG, CI/CD, MERGEABLE

#123 Support Spring
  .gitignore
  Dockerfile
  checkstyle.xml
  docker-compose.yml
  docs/docs/development.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development.md
  pom.xml
  quickstart.sh
  src/main/java/com/paiondata/astraios/App.java
  src/main/java/com/paiondata/astraios/application/BinderFactory.java
  src/main/java/com/paiondata/astraios/application/ResourceConfig.java
  src/main/java/com/paiondata/astraios/config/ElideConfiguration.java
  src/main/java/com/paiondata/astraios/config/FilterConfiguration.java
  src/main/java/com/paiondata/astraios/config/SecurityConfigProperties.java
  src/main/java/com/paiondata/astraios/config/SecurityConfiguration.java
  src/main/java/com/paiondata/astraios/settings/ApplicationConfig.java
  src/main/java/com/paiondata/astraios/settings/JpaDatastoreConfig.java
  src/main/java/com/paiondata/astraios/web/filters/CorsFilter.java
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
  src/main/resources/logback-access-spring.xml
  src/main/resources/logback-spring.xml
  src/main/resources/logback.xml
  src/test/groovy/com/paiondata/astraios/application/ResourceConfigITSpec.groovy
  src/test/groovy/com/paiondata/astraios/application/ResourceConfigSpec.groovy
  src/test/groovy/com/paiondata/astraios/config/AbstractITSpec.groovy
  src/test/groovy/com/paiondata/astraios/config/DockerComposeITSpec.groovy
  src/test/groovy/com/paiondata/astraios/web/filters/CorsFilterSpec.groovy
  src/test/java/com/paiondata/astraios/SpringbootITSpec.java
  src/test/resources/application.properties
  src/test/resources/jpadatastore.properties
  src/test/resources/payload/create-book.json
  src/test/resources/payload/page-sort.json
  src/test/resources/payload/update-book.json
Labels: CI/CD, CONFIG, MERGEABLE, REFACTORING, DOCUMENTATION, BREAKING CHANGE

#126 Fix Bug
  docs/docs/setup.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/setup.md
  src/main/java/com/paiondata/astraios/settings/JpaDatastoreConfig.java
Labels: BUG, MERGEABLE

#131 Add IT test to actuator healthcheckadd test
  src/test/java/com/paiondata/astraios/HealthCheckIntegrationITSpec.java
Labels: CI/CD, MERGEABLE

#134 Support field documentation in GraphQL API via @GraphQLDescription
  src/main/java/com/paiondata/astraios/config/ElideConfiguration.java
Labels: NEW FEATURE, NEED 1 REVIEW
