Repository paion-data/astraios, pull requests merged in 2024-06, with the labels that each got.

#135 Migrating Elide-related doc to paion-data/elide
  docs/docs/elide/_category_.json
  docs/docs/elide/audit.md
  docs/docs/elide/clientapis/_category_.json
  docs/docs/elide/clientapis/asyncapi.mdx
  docs/docs/elide/clientapis/graphql-federation.md
  docs/docs/elide/clientapis/graphql.mdx
  docs/docs/elide/clientapis/img/elide-async-design.drawio
  docs/docs/elide/clientapis/img/elide-async-design.png
  docs/docs/elide/clientapis/img/graphql-federation.png
  docs/docs/elide/clientapis/img/graphql_input_object_uml.png
  docs/docs/elide/clientapis/img/graphql_query_object_uml.png
  docs/docs/elide/clientapis/img/multiple-graphql-apis-federated.png
  docs/docs/elide/clientapis/img/multiple-graphql-apis.png
  docs/docs/elide/clientapis/index.md
  docs/docs/elide/clientapis/jsonapi.mdx
  docs/docs/elide/data-model.md
  docs/docs/elide/datastores.mdx
  docs/docs/elide/features.md
  docs/docs/elide/img/check-tree.png
  docs/docs/elide/img/resource-binding.drawio
  docs/docs/elide/img/resource-binding.png
  docs/docs/elide/img/security-article-comment-uml.png
  docs/docs/elide/openapi.md
  docs/docs/elide/performance.md
  docs/docs/elide/security.mdx
Labels: REFACTORING, DOCUMENTATION

#137 Add year info to Copyright header
  .github/actions/ci-setup/action.yml
  .github/workflows/ci-cd.yml
  Dockerfile
  checkstyle.xml
  docs/.gitignore
  docs/babel.config.js
  docs/docs/configuration.md
  docs/docs/development.md
  docs/docs/intro.mdx
  docs/docs/setup.md
  docs/docusaurus.config.ts
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/configuration.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/development.md
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/setup.md
  docs/sidebars.ts
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/index.module.css
  docs/src/pages/index.tsx
  quickstart.sh
  src/main/java/com/paiondata/astraios/App.java
  src/main/java/com/paiondata/astraios/config/ElideConfiguration.java
  src/main/java/com/paiondata/astraios/config/FilterConfiguration.java
  src/main/java/com/paiondata/astraios/config/SecurityConfigProperties.java
  src/main/java/com/paiondata/astraios/config/SecurityConfiguration.java
  src/main/java/com/paiondata/astraios/settings/ApplicationConfig.java
  src/main/java/com/paiondata/astraios/settings/JpaDatastoreConfig.java
  src/main/resources/application.yaml
  src/main/resources/bootstrap.yaml
  src/test/groovy/com/paiondata/astraios/config/AbstractITSpec.groovy
  src/test/groovy/com/paiondata/astraios/config/DockerComposeITSpec.groovy
  src/test/java/com/paiondata/astraios/HealthCheckIntegrationITSpec.java
  src/test/java/com/paiondata/astraios/SpringbootITSpec.java
  src/test/java/com/paiondata/astraios/models/Book.java
Labels: DOCUMENTATION, NEED 1 REVIEW

#127 Update Elide version form com.yahoo 7.0.0 to com.paiondata 1.0.9
  .github/workflows/ci-cd.yml
  docs/docs/intro.mdx
  docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/intro.mdx
  pom.xml
  quickstart.sh
  settings.xml.example
  src/main/java/com/paiondata/astraios/config/ElideConfiguration.java
  src/main/resources/logback-spring.xml
  src/test/groovy/com/paiondata/astraios/config/AbstractITSpec.groovy
  src/test/java/com/paiondata/astraios/SpringbootITSpec.java
  src/test/java/com/paiondata/astraios/models/Book.java
Labels: REFACTORING
